### ISSUE TITLE
Lack of https

### ISSUE THREAD

**Issue by antitree** [Interlock-Rochester/interlock-rochester.github.io.src#19]

**Comment by antitree** [comment]
Cloud flare provides free options if you want to just on GitHub. Otherwise setting up certbot is simple.

**Comment by deejoe** [comment]
As I've been trying to say since @aks4896 started this move to github, even though I'm not a huge fan of single-vendor proprietary centralized web services, I've sort of made my peace (mostly) with GitHub, especially when we use it in ways (eg, straight up git repo hosting only) that don't rely very much on GitHub-specific stuff. (PR management and issues are problematic under this view, lol).

If folks want to serve up the main web page via GitHub pages, I'm OK with that, but I'm not going to make it happen, on two counts, the one mentioned above, and the other even more practical and immediate. The more practical and immediate one is that that would involve repointing the DNS. That's not in my hands, and since I'm not inclined in this direction anyway I'm not seeking to find out who has to do that and to bug them to do it. DNS points to ghpt's faultline VPS already so that's where I've put the Pelican output to be served up as it is now.

ghpt indicates a willingness to have me much with the web server config so firing up Let's Encrypt one way or another is on my to-do list.

**Comment by deejoe** [comment]
See also https://github.com/Interlock-Rochester/interlock-rochester.github.io/issues/2

**Comment by antitree** [comment]
Setting up cloudflare until the meeting on Tuesday. Blocked by https://github.com/Interlock-Rochester/interlock-rochester.github.io.src/issues/34

**Comment by antitree** [comment]
DNS migrating
